name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Install Playwright Chromium (with deps)
        run: |
          python -m playwright install --with-deps chromium

      - name: Lint (flake8)
        run: |
          flake8 .

      - name: Format check (black)
        run: |
          black --check .

      - name: Type check (mypy)
        run: |
          mypy .

      - name: Run tests
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=. --cov-report=term-missing
