name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install crawl4ai mcp
    
    - name: Test imports
      run: |
        python -c "import crawl4ai, mcp; print('✅ Imports successful')"
    
    - name: Test server module
      run: |
        python -c "import server; print('✅ Server module loads')"
